apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dummy
  namespace: linkerd-project
spec:
  selector:
    matchLabels:
      run: api-dummy
  replicas: 2
  template:
    metadata:
      labels:
        run: api-dummy
    spec:
      containers:
      - name: api-dummy
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: linkerd-project
  labels:
    run: api-dummy
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: api-dummy