apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-kafka
  namespace: kafka_space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-server
        image: pixelcodegg/b-final:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000