apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka_deployment
  namespace: linkerd-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka_client
  template:
    metadata:
      labels:
        app: kafka_client
    spec:
      containers:
      - name: kafka_publisher
        image: battleab/kafka_publisher
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      containers:
      - name: kafka_subscriber
        image: battleab/kafka_subscriber
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka_client
  namespace: linkerd-project
spec:
  ports:
  - name: service
    port: 8080
  selector:
    app: kafka_client