apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: error-split
  namespace: linkerd-project
spec:
  service: api-service
  backends:
  - service: error-injector
    weight: 1000m